### ISSUE TITLE
Microsoft Defender - False Positive

### ISSUE THREAD

**Issue by Groot0075** [keegars/MHR-PrefabFixer#1]
for some reason whenever I try to download the prefab fixer at the one labeled as "Copy Everything" both Opera and Microsoft defender think that particular file is a virus but the other one labeled as "Prefab only" will download just fine though not one I need as I still need to fix my mods

not a hundred percent sure why Microsoft defenders think one of the versions of the prefab fixer is a virus but I figured I should let you know

**Comment by keegars** [comment]
Thanks for alerting me, this can happen at times when a new executable is detected and hasn't encountered it before. With it being new, it can take a few days for defender to be happy with it....happened a few times with some of my programs/mods.

I've submitted it to Microsoft Defender as a false-positive and hopefully will get sorted.

**Comment by Groot0075** [comment]
your welcome glad that I was able to and yeah hopefully this whole thing can get sorted out so people can start using mods again
